// frameworks/echo/src/pages/auth/register/Register.tsx
import './Register.css';
import Checkbox from '../../../components/Checkbox';
import Input from '../../../components/Input';
import type { CustomError } from '../../../utils/types';
import { Link } from 'react-router-dom';
import { useState } from 'react';

const Register = () => {
  let reqErr: CustomError[] = [];
  let err = {email: '', notFound: ''};
  let [email, setEmail] = useState('');
  let [password, setPassword] = useState('');
  let [rememberMe, setRememberMe] = useState(false);

  function submitForm() { console.log('Form submitted') }

  return (
    <section className="register-container">
      <div className="register-form-box">
        <form onSubmit={submitForm} className="register-form">
          {/* Register section */}
          <div className="register-title-container">
            <p className="register-title">Register</p>
          </div> 

          <Input label="Email address" id="email-input" input={email} setInput={setEmail}/>
          
          <Input label="Name" id="email-input" input={email} setInput={setEmail}/>

          <Input label="Password" id="password-input" input={password} setInput={setPassword}/>

          <Input label="Repeat password" id="password-input" input={password} setInput={setPassword}/>

          {err.email && <p className="error-message">{err.email}</p>}
          {err.notFound && <p className="error-message">{err.notFound}</p>}

          {/* register button */}
          <div className="text-center">
            <button type="submit" className="register-btn">Register</button>
            <p className="register-text">
              Already have an account? <Link to="/auth/login" className="register-link">Sign In</Link>
            </p>
          </div>
        </form>
      </div>
    </section>
  );
};

export default Register;

// frameworks/clox/src/app/pages/register/register.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { CommonModule } from '@angular/common';
import { CheckboxComponent } from '../../shared/components/checkbox/checkbox.component';
import { InputComponent } from '../../shared/components/input/input.component';
import { CenteredDivComponent } from '../../shared/components/centered-div/centered-div.component';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [
    CommonModule,
    InputComponent,
    CheckboxComponent,
    CenteredDivComponent,
    ReactiveFormsModule,
    RouterModule,
  ],
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css'],
})
export class RegisterComponent implements OnInit {
  fb = inject(FormBuilder);
  http = inject(HttpClient);
  router = inject(Router);
  authService = inject(AuthService);
  isRegistering: boolean = false;
  err: { email: string; notFound: string } = { email: '', notFound: '' };
  errorMessage!: string;

  form = this.fb.nonNullable.group({
    email: ['', Validators.required],
    username: ['', Validators.required],
    password: ['', Validators.required],
  });

  ngOnInit(): void {
    setTimeout(() => {
      if (this.authService.currentUser()) {
        this.router.navigateByUrl('/');
      }
    }, 0);
  }

  async onSubmit(): Promise<void> {
    console.log('elatla');
    if (this.isRegistering) return;

    try {
      this.isRegistering = true;

      const rawForm = this.form.getRawValue()
      this.authService.register(
        rawForm.email, rawForm.username, rawForm.password
      ).subscribe(result => {
        if (result.error) {
          this.errorMessage = result.error.message;
          this.isRegistering = false;
        } else {
          this.router.navigateByUrl('/');
        }
      })
    } catch (error) {
      console.error(error);
      this.isRegistering = false;
    }
  }
}
<app-centered-div [className]="'register-container'">
  <div class="register-form-box">
    <form [formGroup]="form" (ngSubmit)="onSubmit()" class="register-form">
      <div class="register">
        <p class="register-text">Register</p>
      </div>

      <!-- Separator -->
      <div class="separator">
        <p class="separator-text">o</p>
      </div>

      <app-input
        [required]="true"
        label="Email address"
        id="email-input"
        formControlName="email"
        name="email"
      ></app-input>

      <app-input
        [required]="true"
        label="Username"
        id="username-input"
        formControlName="username"
        name="username"
      ></app-input>

      <app-input
        [required]="true"
        label="Password"
        id="password-input"
        type="password"
        formControlName="password"
        name="password"
      ></app-input>

      <p *ngIf="err.notFound" class="error-message">{{ err.notFound }}</p>

      <!-- register button -->
      <div class="text-center">
        <button type="submit" class="register-btn" [disabled]="isRegistering">
          Register
        </button>

        @if (errorMessage) {
          <div class="error-message">{{ errorMessage }}</div>
        }

        <p class="login-text">
          Already have an account?
          <a routerLink="/login" class="login-link">Sign In</a>
        </p>
      </div>
    </form>
  </div>
</app-centered-div>
