// frameworks/echo/src/pages/auth/login/Login.tsx
import './Login.css';
import Checkbox from '../../../components/Checkbox';
import Input from '../../../components/Input';
import CenteredDiv from '../../../components/CenteredDiv';
import { Link, Navigate } from 'react-router-dom';
import { useState } from 'react'
import { useAuth } from '../../../hooks/useAuth';
import { doSignInWithEmailAndPassword, doSignInWithGoogle } from '../../../firebase/auth';
import type { FormEvent } from 'react';

const Login = () => {
  const { userLoggedIn } = useAuth();

  if (userLoggedIn) {
    return <Navigate to={'/'} replace />
  }

  const [isSigningIn, setIsSigningIn] = useState(false);
  let [email, setEmail] = useState('');
  let [password, setPassword] = useState('');

  const onSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!isSigningIn) {
      try {
        setIsSigningIn(true);
        await doSignInWithEmailAndPassword(email, password);
      } catch (err) {
        console.log(err);
        setIsSigningIn(false);
      }
    }
  }

  const onGoogleSignIn = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if(!isSigningIn) {
      setIsSigningIn(true);
      doSignInWithGoogle().catch(_ => {
        setIsSigningIn(false)
      });
    }
  }

  let err = {email: '', notFound: ''};
  let [rememberMe, setRememberMe] = useState(false);

  return (
    <CenteredDiv className="login-container">
      <div className="login-form-box">
        <form onSubmit={onSubmit} className="login-form">
          {/* Sign in section */}
          <div className="signin-with">
            <p className="signin-with-text">Sign in with</p>
            {/* Google button */}
            <button type="button" className="google-btn">
              <span>
                <svg width="30px" height="30px" viewBox="0 0 45 45" xmlns="http://www.w3.org/2000/svg" className="inline-block align-middle">
                  {/* SVG paths */}
                </svg>
              </span>
            </button>
          </div>

          {/* Separator */}
          <div className="separator">
            <p className="separator-text">Or</p>
          </div>

          <Input
            required
            label="Email address"
            id="email-input"
            input={email}
            setInput={setEmail}
          />

          <Input
            required
            label="Password"
            id="password-input"
            input={password}
            setInput={setPassword}
          />

          {err.email && <p className="error-message">{err.email}</p>}
          {err.notFound && <p className="error-message">{err.notFound}</p>}

          <div className="remember-me">
            {/* Remember me checkbox */}
            <Checkbox
              label="Remember Me"
              checked={rememberMe}
              setChecked={setRememberMe}
            />

            <Link to="#!" className="forgot-password">Forgot password?</Link>
          </div>

          {/* Login button */}
          <div className="text-center">
            <button type="submit" className="login-btn">Login</button>
            <p className="register-text">
              New user? <Link to="/auth/register" className="register-link">Register</Link>
            </p>
          </div>
        </form>
      </div>
    </CenteredDiv>
  );
};

export default Login;

// frameworks/clox/src/app/pages/login/login.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { CommonModule } from '@angular/common';
import { CheckboxComponent } from '../../shared/components/checkbox/checkbox.component';
import { InputComponent } from '../../shared/components/input/input.component';
import { CenteredDivComponent } from '../../shared/components/centered-div/centered-div.component';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [
    CommonModule,
    InputComponent,
    CheckboxComponent,
    CenteredDivComponent,
    ReactiveFormsModule,
    RouterModule,
  ],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent implements OnInit {
  fb = inject(FormBuilder);
  http = inject(HttpClient);
  router = inject(Router);
  authService = inject(AuthService);
  isSigningIn: boolean = false;
  rememberMe: boolean = false;
  err: { email: string; notFound: string } = { email: '', notFound: '' };
  errorMessage!: string;

  form = this.fb.nonNullable.group({
    email: ['', Validators.required],
    password: ['', Validators.required],
  });

  ngOnInit(): void {
    setTimeout(() => {
      if (this.authService.currentUser()) {
        this.router.navigateByUrl('/');
      }
    }, 0);
  }

  async onSubmit(): Promise<void> {
    console.log('elatla');
    if (this.isSigningIn) return;

    try {
      this.isSigningIn = true;

      const rawForm = this.form.getRawValue()
      this.authService.login(
        rawForm.email, rawForm.password
      ).subscribe(result => {
        if (result.error) {
          this.errorMessage = result.error.message;
          this.isSigningIn = false;
        } else {
          this.router.navigateByUrl('/');
        }
      })
    } catch (error) {
      console.error(error);
      this.isSigningIn = false;
    }
  }
}
<app-centered-div [className]="'login-container'">
  <div class="login-form-box">
    <form [formGroup]="form" (ngSubmit)="onSubmit()" class="login-form">
      <!-- Sign in section -->
      <div class="signin-with">
        <p class="signin-with-text">Sign in</p>
      </div>

      <!-- Separator -->
      <div class="separator">
        <p class="separator-text">o</p>
      </div>

      <app-input
        [required]="true"
        label="Email address"
        id="email-input"
        formControlName="email"
        name="email"
      ></app-input>

      <app-input
        [required]="true"
        label="Password"
        id="password-input"
        type="password"
        formControlName="password"
        name="password"
      ></app-input>

      <p *ngIf="err.notFound" class="error-message">{{ err.notFound }}</p>

      <div class="remember-me">
        <app-checkbox
          label="Remember Me"
          [(checked)]="rememberMe"
        ></app-checkbox>

        <a routerLink="/forgot-password" class="forgot-password"
          >Forgot password?</a
        >
      </div>

      <!-- Login button -->
      <div class="text-center">
        <button type="submit" class="login-btn" [disabled]="isSigningIn">
          Sign In
        </button>

        @if (errorMessage) {
          <div class="error-message">{{ errorMessage }}</div>
        }

        <p class="register-text">
          New user?
          <a routerLink="/register" class="register-link">Register</a>
        </p>
      </div>
    </form>
  </div>
</app-centered-div>
