// frameworks/clox/src/app/shared/components/checkbox/checkbox.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-checkbox',
  standalone: true,
  templateUrl: './checkbox.component.html',
  styleUrls: ['./checkbox.component.css']
})
export class CheckboxComponent {
  @Input() label: string = '';
  @Input() id: string = 'checkbox';
  @Input() checked: boolean = false;
  @Output() checkedChange = new EventEmitter<boolean>();

  toggleChecked() {
    this.checked = !this.checked;
    this.checkedChange.emit(this.checked);
  }
}
<div class="checkbox-container">
  <div class="checkbox-icon-container">
    <input
      type="checkbox"
      [id]="id"
      class="checkbox"
      [checked]="checked"
      (change)="toggleChecked()"
    />
    <svg class="checkbox-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
      <path d="M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z"/>
    </svg>
  </div>
  <label [for]="id" class="checkbox-label">{{label}}</label>
</div>

// frameworks/echo/src/components/Checkbox.tsx
import './Checkbox.css';

interface CheckboxProps {
  label?: string,
  id?: string,
  checked: boolean,
  setChecked: React.Dispatch<React.SetStateAction<boolean>>,
}

const Checkbox: React.FC<CheckboxProps> = ({
  label = "",
  id = "checkbox",
  checked = false,
  setChecked,
}) => {
  return (
    <div className="checkbox-container">
      <div className="checkbox-icon-container">
        <input
          type="checkbox"
          id={id}
          className="checkbox"
          checked={checked}
          onChange={() => setChecked(!checked)}
        />
        <svg className="checkbox-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
          <path d="M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z"/>
        </svg>
      </div>
      <label htmlFor={id} className="checkbox-label">{label}</label>
    </div>
  )
}

export default Checkbox
