// frameworks/clox/src/app/shared/components/input/input.component.ts
import { Component, Input, Output, EventEmitter, OnInit, forwardRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

@Component({
  selector: 'app-input',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './input.component.html',
  styleUrls: ['./input.component.css'],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => InputComponent),
      multi: true
    }
  ]
})
export class InputComponent implements OnInit, ControlValueAccessor {
  @Input() label: string = '';
  @Input() id: string = 'input';
  @Input() required: boolean = false;
  @Input() type: string = 'text';
  @Input() err: boolean = false;

  public _inputValue: string = '';

  onChange = (val: any) => {};
  onTouched = () => {};

  writeValue(val: any): void {
    this._inputValue = val;
  }

  registerOnChange(fn: any): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: any): void {
    this.onTouched = fn;
  }

  constructor() {}

  ngOnInit(): void {}

  updateValue(event: Event): void {
    const target = event.target as HTMLInputElement;
    this._inputValue = target.value;
    this.onChange(this._inputValue);
    this.onTouched();
  }
}
<div class="input-container">
  <input
    class="input-field"
    [required]="required"
    [type]="type"
    [class.input-error]="err"
    [id]="id"
    autocomplete="off"
    [value]="_inputValue" 
    (input)="updateValue($event)"
    (blur)="onTouched()"
    placeholder=" "
    #inputField
  />
  <label [htmlFor]="id" class="input-label">{{ label }}</label>
</div>

// frameworks/echo/src/components/Input.tsx
import './Input.css';

interface InputProps {
  input: string,
  label?: string,
  id?: string,
  required?: boolean,
  type?: React.HTMLInputTypeAttribute,
  err?: boolean,
  setInput: React.Dispatch<React.SetStateAction<string>>,
}

const Input: React.FC<InputProps> = ({
  input = "",
  label = "",
  id = "input",
  required = false,
  type = "text",
  err = false,
  setInput,
}) => {
  return (
    <div className="input-container">
      <input
        required={required}
        type={type}
        className={`input-field ${err ? "input-error" : ""}`}
        id={id}
        autoComplete="off"
        value={input}
        onChange={(e) => setInput(e.target.value)}
        placeholder='fdashflkdsah'
      />
      <label htmlFor={id} className="input-label">{label}</label>
    </div>
  )
}

export default Input
